#!/bin/sh

# =============================================================================
#
#        author: Andrii Lytvyn (lytvyn349@gmail.com)
#         POSIX: yes
#   description: set screen wallpaper. supports screen rotation.
#                strongly related to screenr script
#      required: convert(imagemagick), hsetroot
#          args: $1 - file path
#                $2 - hsetroot mode ["center", "cover", "tile",
#                     "full"(default), "extend", "fill" ]
#
# =============================================================================

[ -z "$2" ] && MODE="full" || MODE="$2"
WPATH="$HOME/.local/share/wallpaper"

init() {
    mkdir -p "$WPATH"
    rm "$WPATH/*.png"
}

gen() {
    cp "$1" "$WPATH/normal.png"
    convert "$WPATH/normal.png" -rotate 270 "$WPATH/right.png"
    convert "$WPATH/normal.png" -rotate 90 "$WPATH/left.png"
}

setroot() {
    OR=$(cat "$WPATH"/status)
    case $OR in
        normal | inverted)  hsetroot -"$MODE" "$WPATH/normal.png";;
        right)              hsetroot -"$MODE" "$WPATH/right.png";;
        left)               hsetroot -"$MODE" "$WPATH/left.png";;
    esac
}

setroot_exit() {
    setroot ; exit 0
}

[ -z "$1" ] && setroot_exit

init ; gen "$1" ; setroot
